
services:
  database:
    image: mariadb:latest
    volumes:
      - ./database:/var/lib/mysql
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=somewordpress
      - MARIADB_DATABASE=wordpress
      - MARIADB_USER=wordpress
      - MARIADB_PASSWORD=wordpress
#    ports:
#      - "3306:3306"

  wordpress:
    image: wordpress:latest
    volumes:
      - ./wordpress:/var/www/html
      - ./custom-php.ini:/usr/local/etc/php/conf.d/custom-php.ini # Configurações do PHP
      - ./info.php:/var/www/html/info.php # Comente/Remova essa linha em produção
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - WORDPRESS_DB_HOST=database
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    depends_on:
      - database

#volumes:
#  db_data:
#  wp_data:
