
services:

  database:
    image: mariadb:latest # Database MariaDB
    environment:
      - MARIADB_ROOT_PASSWORD=somewordpress
      - MARIADB_DATABASE=wordpress
      - MARIADB_USER=wordpress
      - MARIADB_PASSWORD=wordpress
#    ports:
#      - '3306:3306'
    volumes:
      - ./database:/var/lib/mysql
    restart: unless-stopped

  wordpress:
    image: wordpress:fpm # Variante Wordpress com FPM
    environment:
      - WORDPRESS_DB_HOST=database
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
#    ports:
#      - '9000:9000'
    volumes:
      - ./wordpress:/var/www/html
      - ./custom-php.ini:/usr/local/etc/php/conf.d/custom-php.ini # Configurações do PHP
      - ./info.php:/var/www/html/info.php # Comente/Remova essa linha em produção
    restart: unless-stopped
    depends_on:
      - database

  nginx:
    image: nginx:latest # Serviço Web Nginx
    ports:
      # - "80:80"
      - "443:443"
    volumes:
      - ./wordpress:/var/www/html # Acesso aos arquivos do WordPress
      - ./custom-nginx.conf:/etc/nginx/conf.d/default.conf # Configurações do Nginx
      - ./nginx.crt:/etc/nginx/ssl/nginx.crt
      - ./nginx.key:/etc/nginx/ssl/nginx.key
    restart: unless-stopped
    depends_on:
      - wordpress
